apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gateway-nginx
resources:
  - namespace.yaml
  - gateway.yaml

helmCharts:
  - name: nginx-gateway-fabric
    repo: oci://ghcr.io/nginxinc/charts
    releaseName: nginx-gateway-fabric
    namespace: gateway-nginx
    includeCRDs: true
    valuesFile: values.yaml
