apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gateway-kong

resources:
  - namespace.yaml
  - gateway.yaml

helmCharts:
  - name: ingress
    repo: https://charts.konghq.com
    version: 0.22.0                   # Latest stable version
    releaseName: kong
    namespace: gateway-kong
    includeCRDs: false                # CRDs installed separately
    valuesFile: values.yaml
