kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  labels:
    tier: postgres-storage
  name: postgres-storage
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi