kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: immich-pvc
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
#  volumeName: immich-pvc